version: "3.8"
services:
    mariadb:
        image: mariadb
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=wordpress
        volumes:
            - ./database:/var/lib/mysql
        networks:
            rede_interna:

    wordpress:
        image: wordpress
        environment:
            - WORDPRESS_DB_PASSWORD=password
            - WORDPRESS_DB_HOST=mariadb
        ports:
            - 80:80
        volumes:
            - ./html:/var/www/html
        networks:
            rede_interna:

networks:
    rede_interna:
        driver: bridge
        ipam:
            config:
                - subnet: 172.28.0.0/16
