version: "3.8"
services:
  wordpress:
    image: wordpress
    user: root
    command: chown -R 1000:1000 /var/www/html
    links:
      - mariadb:mysql
    environment:
      - WORDPRESS_DB_PASSWORD=senha
    ports:
      - 80:80
    volumes:
      - ./html:/var/www/html

  mariadb:
    image: mariadb
    user: root
    command: chown -R 1000:1000 /var/lib/mysql
    environment:

      - MYSQL_ROOT_PASSWORD=senha
      - MYSQL_DATABASE=wordpress
    volumes:
      - ./database:/var/lib/mysql

volumes:
  html:
  database:
